sonar.projectKey=uo289165_epi-climanuvem
sonar.organization=uo289165

sonar.sources=backend/app,frontend/src,frontend/app,frontend/components,frontend/hooks
sonar.tests=backend/tests,frontend/__tests__

sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

sonar.coverage.exclusions=**/locales/**,backend/app/infrastructure/database/seed_clouds.sql

