sonar.projectKey=uo289165_epi-climanuvem
sonar.organization=uo289165-1

sonar.sources=backend/app,frontend/src,frontend/app,frontend/components,frontend/hooks
sonar.tests=backend/tests,frontend/__tests__

sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

sonar.coverage.exclusions=**/locales/**,backend/app/infrastructure/database/seed_clouds.sql,backend/app/infrastructure/database/migrations/**,frontend/app/**,frontend/components/**,frontend/src/views/**,frontend/src/styles/**,frontend/src/config/**,frontend/src/controllers/**,frontend/src/hooks/**,frontend/src/i18n.ts,frontend/src/services/AuthService.ts,frontend/src/services/LoggerService.ts,frontend/src/services/NotificationService.ts,frontend/src/services/mockData.ts,frontend/src/utils/captureUtils.ts,frontend/src/models/**
